/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import calculator.calc.Machine;
import calculator.library.LibraryOperators;
import calculator.order.IInstructionSet;
import calculator.order.InstructionFactory;
import calculator.order.InstructionSet;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        LibraryOperators libraryOperators= new LibraryOperators();
        BufferedReader bufferedReader = new BufferedReader(new FileReader("/home/tomek/Documents/CV/storware/Calculator/src/main/resources/instructions.txt"));
        IInstructionSet instructionSet = new InstructionSet(new InstructionFactory(), bufferedReader);
        Machine machine = new Machine(libraryOperators, instructionSet);
        int result = machine.calculate();
        System.out.println(result);
    }
}
