/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import calculator.calc.Calculator;
import calculator.file.loader.FileLoader;
import calculator.library.LibraryOperators;
import calculator.instruction.InstructionFactory;
import calculator.instruction.InstructionsFile;

import java.io.IOException;
import java.math.BigDecimal;

public class App {
    public static void main(String[] args) throws IOException {
        LibraryOperators libraryOperators= new LibraryOperators();
        FileLoader fileLoader = new FileLoader();

        InstructionsFile instructionsFile = new InstructionsFile(new InstructionFactory(), fileLoader.getInstructionFile(args));
        Calculator calculator = new Calculator(libraryOperators, instructionsFile);
        BigDecimal result = calculator.calculate();
        System.out.println(result);
    }
}

